import { LevelCampaign, WeaponType } from '../types/GameTypes';
import { HERO_TYPES, ENEMY_TYPES } from './GameConfig';

export const CAMPAIGN_LEVELS: LevelCampaign[] = [
  {
    id: 'tutorial',
    name: 'Training Grounds',
    description: 'Learn the basics of cooperative gameplay',
    difficulty: 'easy',
    unlockConditions: {
      requiredLevel: 0,
    },
    rewards: {
      bonusScore: 1000,
      achievements: ['First Steps'],
    },
    levelData: {
      playerStart: { x: 1, y: 17 },
      enemies: [
        {
          id: 'tutorial-enemy-1',
          position: { x: 10, y: 10 },
          originalPosition: { x: 10, y: 10 },
          patrolRadius: 2,
          color: '#ef4444',
          borderColor: '#dc2626',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 1,
          maxHealth: 1,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[0],
          moveSpeed: 1000,
          shootCooldown: 1500,
          shootRange: 4,
          startDirection: { x: 1, y: 0 },
          behaviorPattern: 'patrol',
        },
      ],
      walls: [],
      collectibleHeroes: [
        {
          id: 'tutorial-hero-1',
          position: { x: 15, y: 8 },
          heroType: HERO_TYPES[1], // Scout
          collected: false,
        },
      ],
      powerUps: [
        {
          id: 'tutorial-powerup-1',
          position: { x: 5, y: 5 },
          type: 'speedBoost',
          collected: false,
        },
      ],
      exitZones: [
        {
          id: 'tutorial-exit-1',
          position: { x: 20, y: 2 },
        },
      ],
      metadata: {
        name: 'Training Grounds',
        author: 'System',
        description: 'Tutorial level',
        version: '1.0',
        createdAt: new Date().toISOString(),
        modifiedAt: new Date().toISOString(),
        difficulty: 'easy',
        tags: ['tutorial'],
        timeLimit: 300,
      },
      editorObjects: [
        {
          id: 'tutorial-exit-obj',
          type: 'exit',
          position: { x: 20, y: 2 },
          config: {},
        },
      ],
    },
    difficultyScaling: {
      enemyCount: 1,
      enemyHealthMultiplier: 1,
      timeLimit: 300,
    },
  },
  {
    id: 'urban-assault',
    name: 'Urban Assault',
    description: 'Navigate through city streets filled with enemies',
    difficulty: 'easy',
    unlockConditions: {
      requiredLevel: 1,
    },
    rewards: {
      unlockedHeroes: ['ranger'],
      bonusScore: 1500,
      achievements: ['City Survivor'],
    },
    levelData: {
      playerStart: { x: 2, y: 16 },
      enemies: [
        {
          id: 'urban-enemy-1',
          position: { x: 8, y: 12 },
          originalPosition: { x: 8, y: 12 },
          patrolRadius: 3,
          color: '#ef4444',
          borderColor: '#dc2626',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 2,
          maxHealth: 2,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[0],
          moveSpeed: 800,
          shootCooldown: 1000,
          shootRange: 5,
          startDirection: { x: 1, y: 0 },
          behaviorPattern: 'patrol',
        },
        {
          id: 'urban-enemy-2',
          position: { x: 15, y: 8 },
          originalPosition: { x: 15, y: 8 },
          patrolRadius: 2,
          color: '#8b5cf6',
          borderColor: '#7c3aed',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 1,
          maxHealth: 1,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[1],
          moveSpeed: 1200,
          shootCooldown: 600,
          shootRange: 8,
          startDirection: { x: -1, y: 0 },
          behaviorPattern: 'guard',
        },
      ],
      walls: [
        { id: 'wall-1', position: { x: 10, y: 10 } },
        { id: 'wall-2', position: { x: 11, y: 10 } },
        { id: 'wall-3', position: { x: 12, y: 10 } },
        { id: 'wall-4', position: { x: 6, y: 6 } },
        { id: 'wall-5', position: { x: 7, y: 6 } },
        { id: 'wall-6', position: { x: 8, y: 6 } },
      ],
      collectibleHeroes: [
        {
          id: 'urban-hero-1',
          position: { x: 18, y: 12 },
          heroType: HERO_TYPES[2], // Tank
          collected: false,
        },
      ],
      powerUps: [
        {
          id: 'urban-powerup-1',
          position: { x: 5, y: 8 },
          type: 'rapidFire',
          collected: false,
        },
        {
          id: 'urban-powerup-2',
          position: { x: 12, y: 4 },
          type: 'shield',
          collected: false,
        },
      ],
      exitZones: [
        {
          id: 'urban-exit-1',
          position: { x: 22, y: 1 },
        },
      ],
      metadata: {
        name: 'Urban Assault',
        author: 'System',
        description: 'City combat scenario',
        version: '1.0',
        createdAt: new Date().toISOString(),
        modifiedAt: new Date().toISOString(),
        difficulty: 'easy',
        tags: ['urban', 'combat'],
        timeLimit: 240,
      },
      editorObjects: [
        {
          id: 'urban-exit-obj',
          type: 'exit',
          position: { x: 22, y: 1 },
          config: {},
        },
      ],
    },
    difficultyScaling: {
      enemyCount: 2,
      enemyHealthMultiplier: 1.2,
      timeLimit: 240,
    },
  },
  {
    id: 'fortress-siege',
    name: 'Fortress Siege',
    description: 'Assault a heavily fortified enemy stronghold',
    difficulty: 'medium',
    unlockConditions: {
      requiredLevel: 2,
      requiredScore: 3000,
    },
    rewards: {
      unlockedHeroes: ['ninja'],
      unlockedWeapons: [WeaponType.THROWING_STAR],
      bonusScore: 2500,
      achievements: ['Fortress Breaker'],
    },
    levelData: {
      playerStart: { x: 1, y: 15 },
      enemies: [
        {
          id: 'fortress-enemy-1',
          position: { x: 12, y: 12 },
          originalPosition: { x: 12, y: 12 },
          patrolRadius: 4,
          color: '#059669',
          borderColor: '#047857',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 4,
          maxHealth: 4,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[2],
          moveSpeed: 1500,
          shootCooldown: 1500,
          shootRange: 4,
          startDirection: { x: 0, y: 1 },
          behaviorPattern: 'aggressive',
        },
        {
          id: 'fortress-enemy-2',
          position: { x: 18, y: 8 },
          originalPosition: { x: 18, y: 8 },
          patrolRadius: 2,
          color: '#8b5cf6',
          borderColor: '#7c3aed',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 1,
          maxHealth: 1,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[1],
          moveSpeed: 1200,
          shootCooldown: 600,
          shootRange: 8,
          startDirection: { x: -1, y: 0 },
          behaviorPattern: 'guard',
        },
        {
          id: 'fortress-enemy-3',
          position: { x: 6, y: 6 },
          originalPosition: { x: 6, y: 6 },
          patrolRadius: 3,
          color: '#f59e0b',
          borderColor: '#d97706',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 1,
          maxHealth: 1,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[3],
          moveSpeed: 400,
          shootCooldown: 800,
          shootRange: 3,
          startDirection: { x: 0, y: -1 },
          behaviorPattern: 'aggressive',
        },
      ],
      walls: [
        // Fortress walls
        { id: 'wall-1', position: { x: 14, y: 8 } },
        { id: 'wall-2', position: { x: 15, y: 8 } },
        { id: 'wall-3', position: { x: 16, y: 8 } },
        { id: 'wall-4', position: { x: 17, y: 8 } },
        { id: 'wall-5', position: { x: 14, y: 9 } },
        { id: 'wall-6', position: { x: 17, y: 9 } },
        { id: 'wall-7', position: { x: 14, y: 10 } },
        { id: 'wall-8', position: { x: 17, y: 10 } },
        { id: 'wall-9', position: { x: 14, y: 11 } },
        { id: 'wall-10', position: { x: 15, y: 11 } },
        { id: 'wall-11', position: { x: 16, y: 11 } },
        { id: 'wall-12', position: { x: 17, y: 11 } },
      ],
      collectibleHeroes: [
        {
          id: 'fortress-hero-1',
          position: { x: 15, y: 9 },
          heroType: HERO_TYPES[4], // Ninja
          collected: false,
        },
        {
          id: 'fortress-hero-2',
          position: { x: 20, y: 14 },
          heroType: HERO_TYPES[0], // Warrior
          collected: false,
        },
      ],
      powerUps: [
        {
          id: 'fortress-powerup-1',
          position: { x: 8, y: 10 },
          type: 'rapidFire',
          collected: false,
        },
      ],
      exitZones: [
        {
          id: 'fortress-exit-1',
          position: { x: 23, y: 2 },
        },
      ],
      metadata: {
        name: 'Fortress Siege',
        author: 'System',
        description: 'Fortress assault mission',
        version: '1.0',
        createdAt: new Date().toISOString(),
        modifiedAt: new Date().toISOString(),
        difficulty: 'medium',
        tags: ['fortress', 'siege'],
        timeLimit: 180,
      },
      editorObjects: [
        {
          id: 'fortress-exit-obj',
          type: 'exit',
          position: { x: 23, y: 2 },
          config: {},
        },
      ],
    },
    difficultyScaling: {
      enemyCount: 3,
      enemyHealthMultiplier: 1.5,
      timeLimit: 180,
      additionalObjectives: ['Rescue all captives'],
    },
  },
  {
    id: 'final-showdown',
    name: 'Final Showdown',
    description: 'The ultimate test of cooperative teamwork',
    difficulty: 'expert',
    unlockConditions: {
      requiredLevel: 3,
      requiredScore: 8000,
      mustRescueAll: true,
    },
    rewards: {
      unlockedHeroes: ['mage', 'viking', 'archer'],
      unlockedWeapons: [WeaponType.MAGIC_BOLT, WeaponType.AXE, WeaponType.BOW],
      bonusScore: 5000,
      achievements: ['Master Tactician', 'Perfect Cooperation', 'Campaign Complete'],
    },
    levelData: {
      playerStart: { x: 2, y: 17 },
      enemies: [
        {
          id: 'final-enemy-1',
          position: { x: 12, y: 12 },
          originalPosition: { x: 12, y: 12 },
          patrolRadius: 5,
          color: '#059669',
          borderColor: '#047857',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 6,
          maxHealth: 6,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[2],
          moveSpeed: 1200,
          shootCooldown: 1200,
          shootRange: 6,
          startDirection: { x: 0, y: 1 },
          behaviorPattern: 'aggressive',
        },
        {
          id: 'final-enemy-2',
          position: { x: 20, y: 8 },
          originalPosition: { x: 20, y: 8 },
          patrolRadius: 3,
          color: '#8b5cf6',
          borderColor: '#7c3aed',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 2,
          maxHealth: 2,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[1],
          moveSpeed: 1000,
          shootCooldown: 500,
          shootRange: 10,
          startDirection: { x: -1, y: 0 },
          behaviorPattern: 'guard',
        },
        {
          id: 'final-enemy-3',
          position: { x: 6, y: 6 },
          originalPosition: { x: 6, y: 6 },
          patrolRadius: 4,
          color: '#f59e0b',
          borderColor: '#d97706',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 2,
          maxHealth: 2,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[3],
          moveSpeed: 300,
          shootCooldown: 600,
          shootRange: 4,
          startDirection: { x: 0, y: -1 },
          behaviorPattern: 'aggressive',
        },
        {
          id: 'final-enemy-4',
          position: { x: 15, y: 15 },
          originalPosition: { x: 15, y: 15 },
          patrolRadius: 3,
          color: '#ef4444',
          borderColor: '#dc2626',
          isChasing: false,
          lastMoveTime: 0,
          lastShootTime: 0,
          canShoot: true,
          health: 3,
          maxHealth: 3,
          isHit: false,
          hitTime: 0,
          isDestroyed: false,
          destroyTime: 0,
          enemyType: ENEMY_TYPES[0],
          moveSpeed: 600,
          shootCooldown: 800,
          shootRange: 6,
          startDirection: { x: 1, y: 0 },
          behaviorPattern: 'patrol',
        },
      ],
      walls: [
        // Complex maze-like structure
        { id: 'wall-1', position: { x: 8, y: 8 } },
        { id: 'wall-2', position: { x: 9, y: 8 } },
        { id: 'wall-3', position: { x: 10, y: 8 } },
        { id: 'wall-4', position: { x: 8, y: 9 } },
        { id: 'wall-5', position: { x: 10, y: 9 } },
        { id: 'wall-6', position: { x: 8, y: 10 } },
        { id: 'wall-7', position: { x: 9, y: 10 } },
        { id: 'wall-8', position: { x: 10, y: 10 } },
        { id: 'wall-9', position: { x: 16, y: 12 } },
        { id: 'wall-10', position: { x: 17, y: 12 } },
        { id: 'wall-11', position: { x: 18, y: 12 } },
        { id: 'wall-12', position: { x: 16, y: 13 } },
        { id: 'wall-13', position: { x: 18, y: 13 } },
        { id: 'wall-14', position: { x: 16, y: 14 } },
        { id: 'wall-15', position: { x: 17, y: 14 } },
        { id: 'wall-16', position: { x: 18, y: 14 } },
      ],
      collectibleHeroes: [
        {
          id: 'final-hero-1',
          position: { x: 9, y: 9 },
          heroType: HERO_TYPES[5], // Mage
          collected: false,
        },
        {
          id: 'final-hero-2',
          position: { x: 17, y: 13 },
          heroType: HERO_TYPES[6], // Viking
          collected: false,
        },
        {
          id: 'final-hero-3',
          position: { x: 22, y: 16 },
          heroType: HERO_TYPES[7], // Archer
          collected: false,
        },
      ],
      powerUps: [
        {
          id: 'final-powerup-1',
          position: { x: 4, y: 4 },
          type: 'speedBoost',
          collected: false,
        },
        {
          id: 'final-powerup-2',
          position: { x: 14, y: 6 },
          type: 'rapidFire',
          collected: false,
        },
        {
          id: 'final-powerup-3',
          position: { x: 20, y: 16 },
          type: 'shield',
          collected: false,
        },
      ],
      exitZones: [
        {
          id: 'final-exit-1',
          position: { x: 24, y: 1 },
        },
      ],
      metadata: {
        name: 'Final Showdown',
        author: 'System',
        description: 'Ultimate challenge',
        version: '1.0',
        createdAt: new Date().toISOString(),
        modifiedAt: new Date().toISOString(),
        difficulty: 'expert',
        tags: ['final', 'boss', 'challenge'],
        timeLimit: 120,
      },
      editorObjects: [
        {
          id: 'final-exit-obj',
          type: 'exit',
          position: { x: 24, y: 1 },
          config: {},
        },
      ],
    },
    difficultyScaling: {
      enemyCount: 4,
      enemyHealthMultiplier: 2,
      timeLimit: 120,
      additionalObjectives: ['Rescue all captives', 'Perfect run required'],
    },
  },
];

export const ACHIEVEMENT_DEFINITIONS = {
  'First Steps': {
    name: 'First Steps',
    description: 'Complete your first level',
    icon: '🎯',
    points: 100,
  },
  'City Survivor': {
    name: 'City Survivor',
    description: 'Survive the urban assault',
    icon: '🏙️',
    points: 200,
  },
  'Fortress Breaker': {
    name: 'Fortress Breaker',
    description: 'Successfully assault the fortress',
    icon: '🏰',
    points: 300,
  },
  'Master Tactician': {
    name: 'Master Tactician',
    description: 'Complete all campaign levels',
    icon: '🎖️',
    points: 500,
  },
  'Perfect Cooperation': {
    name: 'Perfect Cooperation',
    description: 'Complete a level without any player taking damage',
    icon: '🤝',
    points: 400,
  },
  'Campaign Complete': {
    name: 'Campaign Complete',
    description: 'Finish the entire campaign',
    icon: '👑',
    points: 1000,
  },
  'Speed Runner': {
    name: 'Speed Runner',
    description: 'Complete a level in record time',
    icon: '⚡',
    points: 300,
  },
  'Rescue Master': {
    name: 'Rescue Master',
    description: 'Rescue all captives in every level',
    icon: '🛡️',
    points: 400,
  },
};